CAPABILITIES = {
    3: {"status": "legacy", "tools": ["modelo_dominio", "base_inteligente", "conferencia_extrato", "conferencia_fiscal"]},
    47: {"status": "adapter_pending", "banks": {"banco_brasil": "8"}},
    88: {"status": "api_ready", "banks": {"itau": "508"}},
    154: {"status": "adapter_pending", "banks": {"bradesco": "9", "itau": "508"}},
    178: {"status": "legacy", "tools": ["modelo_dominio", "base_inteligente", "conferencia_extrato", "conferencia_fiscal"]},
    242: {"status": "legacy_complex", "banks": {"itau_508": "508", "itau_509": "509"}},
    266: {"status": "legacy_complex"},
    285: {"status": "legacy_complex"},
    343: {"status": "legacy"},
    625: {"status": "api_ready", "banks": {"banco_brasil": "8", "caixa": "508", "sicredi": "3999"}},
    626: {"status": "api_ready", "banks": {"banco_brasil": "", "sicredi": ""}},
    841: {"status": "api_ready", "banks": {"inter": "506"}},
    912: {"status": "adapter_pending", "banks": {"sicredi": "515"}},
    964: {"status": "adapter_pending", "banks": {"bradesco": "9"}},
    968: {"status": "legacy_complex", "banks": {"itau": "508", "bradesco": "9"}},
    969: {"status": "api_ready", "banks": {"itau": "508"}},
    1000: {"status": "legacy_complex"},
    1001: {"status": "legacy_complex"},
    1096: {"status": "legacy_complex", "banks": {"santander": "513", "sicredi": "510"}},
    1208: {"status": "api_ready", "banks": {"itau": "508", "safra": "512", "bradesco": "9"}},
    1211: {"status": "legacy_complex"},
    1396: {"status": "legacy_complex"},
    1402: {"status": "api_ready_pair", "banks": {"btg": "510"}},
    1408: {"status": "legacy_complex", "banks": {"itau": "512"}},
    1529: {"status": "legacy"},
    1530: {"status": "api_ready_xls", "banks": {"itau": "508"}},
    1532: {"status": "adapter_pending", "banks": {"itau": "508"}},
}
